# environment
SCREEN_WIDTH: int = 1280
SCREEN_HEIGHT: int  = 720
LINE_WIDTH: int = 2

# player
PLAYER_RADIUS: int = 20
PLAYER_TURN_SPEED: int = 300
PLAYER_SPEED: int = 200

# asteroids
ASTEROID_MIN_RADIUS: int = 20
ASTEROID_KINDS: int = 3
ASTEROID_SPAWN_RATE_SECONDS: float = 0.8
ASTEROID_MAX_RADIUS: int = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

# colors
SCREEN_FILL_COLOR: str = "black"
PLAYER_COLOR: str = "white"
ASTEROID_COLOR: str = "white"
